services:
  db:
    image: postgres:16-alpine
    container_name: fastapi_zero_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_zero
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d fastapi_zero" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
